name: Deploy Angular PWA to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'fe/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: fe/package-lock.json

      - name: Install Dependencies
        run: cd fe && npm ci

      - name: Build Angular Project
        run: cd fe && npm run build -- --configuration=production --base-href=/cheap-food/
        # Note : Remplacez /cheap-food/ par le nom exact de votre dépôt GitHub s'il change

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Angular compile le projet dans un sous-dossier de 'dist/'
          path: './fe/dist/cheap-food/browser' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
